services:
  - type: web
    name: securix
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --timeout 120
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: GROQ_API_KEY
        sync: false
      - key: VIRUSTOTAL_API_KEY
        sync: false
      - key: CLOUDFLARE_RADAR_TOKEN
        sync: false
      - key: GOOGLE_SAFEBROWSING_KEY
        sync: false
      - key: ABUSEIPDB_KEY
        sync: false
      - key: HIBP_API_KEY
        sync: false
      - key: NUMLOOKUP_API_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: ADMIN_USERNAME
        value: "billy"
      - key: PYTHON_VERSION
        value: "3.11.0"
